// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YT_Community.DBContext;

#nullable disable

namespace YT_Community.Migrations
{
    [DbContext(typeof(YoutubeCommunityContext))]
    [Migration("20250125112652_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YT_Community.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MobileNumber")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            DateOfBirth = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karthic@gmail.com",
                            MobileNumber = 1234567890L,
                            PasswordHash = "123",
                            UserName = "User1"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            DateOfBirth = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "raja@gmail.com",
                            MobileNumber = 1234567890L,
                            PasswordHash = "123",
                            UserName = "User2"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            DateOfBirth = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kr@gmail.com",
                            MobileNumber = 1234567890L,
                            PasswordHash = "123",
                            UserName = "User3"
                        });
                });

            modelBuilder.Entity("YT_Community.Models.VideoLink", b =>
                {
                    b.Property<Guid>("VideoLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VideoLinkId");

                    b.ToTable("VideoLinks");

                    b.HasData(
                        new
                        {
                            VideoLinkId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Description = "This is a video link",
                            Domain = "Youtube",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.youtube.com/watch?v=123456",
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            VideoLinkId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "This is a video link",
                            Domain = "Youtube",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.youtube.com/watch?v=123457",
                            UserId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            VideoLinkId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Description = "This is a video link",
                            Domain = "Youtube",
                            PostedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Url = "https://www.youtube.com/watch?v=123458",
                            UserId = new Guid("00000000-0000-0000-0000-000000000003")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
